Use RequestBody data guard
Summary:
Rocket allows in debug to read request body as a string,
but not in production. Switching to RequestBody implementation
provided by Limiting Factor for such cases.

This change fixes the following issue:

    error[E0277]: the trait bound `std::string::String: FromDataSimple`
    is not satisfied

Fixes T1827.

Test Plan: Fire HTTP requests to deploy/init/update

Reviewers: dereckson

Reviewed By: dereckson

Maniphest Tasks: T1827

Differential Revision: https://devcentral.nasqueron.org/D2995